# Generated by Django 4.1.6 on 2023-02-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to='media/% Y/% m/% d/'),
        ),
    ]
