# Generated by Django 4.1.6 on 2023-02-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_delete_filemodel_alter_document_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('myfiles', models.FileField(upload_to='')),
            ],
        ),
    ]
