# Generated by Django 4.1.6 on 2023-02-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_myuploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='f_name',
        ),
    ]
