# Generated by Django 4.1.6 on 2023-02-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_remove_myuploadfile_f_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myuploadfile',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='files',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
