# Generated by Django 4.1.6 on 2023-02-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0009_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
            ],
        ),
    ]
