# Generated by Django 4.1.6 on 2023-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0010_filenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='on_stock',
            field=models.CharField(max_length=255),
        ),
    ]
