# Generated by Django 4.1.6 on 2023-02-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0015_alter_products_dealer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dealer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detector.dialer'),
        ),
    ]
