# Generated by Django 4.1.6 on 2023-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0017_alter_products_dealer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='dealer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
