# Generated by Django 4.1.6 on 2023-02-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0018_alter_dialer_name_alter_products_dealer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dialer',
        ),
    ]
