# Generated by Django 4.1.6 on 2023-02-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0019_delete_dialer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
