# Generated by Django 4.1.6 on 2023-02-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0020_products_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='part_number2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='part_number3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='part_number4',
        ),
        migrations.AlterField(
            model_name='products',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
