# Generated by Django 4.1.6 on 2023-02-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0025_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='shape',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
