# Generated by Django 4.1.6 on 2023-02-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0026_products_filename_products_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenames',
            name='filename2',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
