# Generated by Django 4.1.6 on 2023-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0027_filenames_filename2'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenames',
            name='dealer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filenames',
            name='shape',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
