# Generated by Django 4.1.6 on 2023-02-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0028_filenames_dealer_name_filenames_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('shape', models.CharField(max_length=255)),
                ('uploaded_on', models.DateTimeField(null=models.CharField(max_length=255))),
            ],
        ),
    ]
