# Generated by Django 4.1.6 on 2023-02-19 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0030_alter_products_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 20, 0, 40, 3462)),
        ),
    ]
