# Generated by Django 4.1.6 on 2023-02-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0032_alter_products_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remove', models.CharField(blank=True, max_length=200, null=True)),
                ('see', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
